# Generated by Django 4.2.4 on 2023-09-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timers", "0008_pause"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pause",
        ),
    ]
