# Generated by Django 4.2.4 on 2023-08-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="name"
                    ),
                ),
                (
                    "wanted_duration",
                    models.DurationField(verbose_name="wanted duration"),
                ),
            ],
        ),
    ]
