# Generated by Django 4.2.4 on 2023-08-07 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
        ("tasks", "0002_task_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="frequency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="schedules.frequency",
                verbose_name="frequency",
            ),
        ),
    ]
