# Generated by Django 4.2.4 on 2023-09-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="previous_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="next_version",
                to="tasks.task",
                verbose_name="previous version",
            ),
        ),
    ]
