# Generated by Django 4.2.4 on 2023-09-16 07:58

from django.db import migrations, models
from timers.models import Timer
from django.contrib.contenttypes.models import ContentType
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pauses", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pause",
            name="timer",
        ),
        migrations.AddField(
            model_name="pause",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["Timer", "Task"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
                default=ContentType.objects.get_for_model(Timer).id,
            ),
        ),
        migrations.AddField(
            model_name="pause",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
