# Generated by Django 4.2.4 on 2023-09-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pauses", "0002_remove_pause_timer_pause_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pause",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["Timer", "Task"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="pause",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
