# Generated by Django 4.2.4 on 2023-09-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pauses", "0003_alter_pause_content_type_alter_pause_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pause",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "timers"), ("model", "timer")),
                    models.Q(("app_label", "tasks"), ("model", "task")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
