# Generated by Django 4.2.4 on 2023-08-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "events_number",
                    models.PositiveIntegerField(verbose_name="events number"),
                ),
                (
                    "time_unit",
                    models.CharField(
                        choices=[
                            ("day", "day"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=32,
                        verbose_name="time unit",
                    ),
                ),
            ],
        ),
    ]
